export const RANKS = [
  {
    name: 'Bronze',
    divisions: ['IV', 'III', 'II', 'I'],
    color: 'from-amber-700 to-amber-900',
    borderColor: 'border-amber-600/50',
    icon: `${import.meta.env.VITE_CDN_URL}/leagues/icons/bronze.svg`,
  },
  {
    name: 'Silver',
    divisions: ['IV', 'III', 'II', 'I'],
    color: 'from-slate-400 to-slate-600',
    borderColor: 'border-slate-400/50',
    icon: `${import.meta.env.VITE_CDN_URL}/leagues/icons/silver.svg`,
  },
  {
    name: 'Gold',
    divisions: ['IV', 'III', 'II', 'I'],
    color: 'from-yellow-500 to-yellow-700',
    borderColor: 'border-yellow-500/50',
    icon: `${import.meta.env.VITE_CDN_URL}/leagues/icons/gold.svg`,
  },
  {
    name: 'Diamond',
    divisions: ['IV', 'III', 'II', 'I'],
    color: 'from-cyan-400 to-cyan-600',
    borderColor: 'border-cyan-400/50',
    icon: `${import.meta.env.VITE_CDN_URL}/leagues/icons/diamond.svg`,
  },
  {
    name: 'Master',
    divisions: null,
    color: 'from-purple-500 to-purple-700',
    borderColor: 'border-purple-500/50',
    icon: `${import.meta.env.VITE_CDN_URL}/leagues/icons/master.svg`,
  },
  {
    name: 'Challenger',
    divisions: null,
    color: 'from-gold-4 to-gold-6',
    borderColor: 'border-gold-4/50',
    icon: `${import.meta.env.VITE_CDN_URL}/leagues/icons/challenger.svg`,
    special: true,
  },
]
