env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  prettier/prettier:
    - error
    - printWidth: 80
      tabWidth: 2
      singleQuote: true
      trailingComma: all
      arrowParens: always
      semi: false
      endOfLine: lf
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: off
  "@typescript-eslint/no-this-alias":
    - error
    - allowedNames:
        - self
  "@typescript-eslint/no-var-requires": off

