# https://docs.docker.com/go/compose-spec-reference/

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      FIREBASE_ADMIN_CREDENTIALS: ${FIREBASE_ADMIN_CREDENTIALS}
      MAGIC3T_BACKEND_URL: http://server
      HEARTBEAT_RATE: ${HEARTBEAT_RATE}
      PORT: 80
    ports:
      - ${PORT}:80

  redis:
    image: redis:latest
    ports:
      - "6379:6379"