# syntax=docker/dockerfile:1
# https://docs.docker.com/go/dockerfile-reference/

FROM node:alpine AS base
COPY . /app
WORKDIR /app
RUN npm clean-install

WORKDIR /app/backend
RUN echo $SENTRY_AUTH_TOKEN
RUN npm run build
USER node
WORKDIR /app/backend
ENTRYPOINT [ "npm", "run", "start:prod" ]
