/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as BiancaRouteImport } from './routes/bianca'
import { Route as AuthGuardedRouteImport } from './routes/_auth-guarded'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as TutorialRouteRouteImport } from './routes/tutorial/route'
import { Route as AuthGuardedIndexRouteImport } from './routes/_auth-guarded/index'
import { Route as UsersNicknameRouteImport } from './routes/users/$nickname'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthGuardedStoreRouteImport } from './routes/_auth-guarded/store'
import { Route as AuthGuardedAdminRouteImport } from './routes/_auth-guarded/admin'
import { Route as AuthGuardedMeRouteRouteImport } from './routes/_auth-guarded/me/route'
import { Route as UsersIdUserIdRouteImport } from './routes/users/id/$userId'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BiancaRoute = BiancaRouteImport.update({
  id: '/bianca',
  path: '/bianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardedRoute = AuthGuardedRouteImport.update({
  id: '/_auth-guarded',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRouteRoute = TutorialRouteRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardedIndexRoute = AuthGuardedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGuardedRoute,
} as any)
const UsersNicknameRoute = UsersNicknameRouteImport.update({
  id: '/users/$nickname',
  path: '/users/$nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuardedStoreRoute = AuthGuardedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthGuardedRoute,
} as any)
const AuthGuardedAdminRoute = AuthGuardedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthGuardedRoute,
} as any)
const AuthGuardedMeRouteRoute = AuthGuardedMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthGuardedRoute,
} as any)
const UsersIdUserIdRoute = UsersIdUserIdRouteImport.update({
  id: '/users/id/$userId',
  path: '/users/id/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/tutorial': typeof TutorialRouteRoute
  '/': typeof AuthGuardedIndexRoute
  '/bianca': typeof BiancaRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof AuthGuardedMeRouteRoute
  '/admin': typeof AuthGuardedAdminRoute
  '/store': typeof AuthGuardedStoreRoute
  '/register': typeof AuthRegisterRoute
  '/sign-in': typeof AuthSignInRoute
  '/users/$nickname': typeof UsersNicknameRoute
  '/users/id/$userId': typeof UsersIdUserIdRoute
}
export interface FileRoutesByTo {
  '/tutorial': typeof TutorialRouteRoute
  '/': typeof AuthGuardedIndexRoute
  '/bianca': typeof BiancaRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof AuthGuardedMeRouteRoute
  '/admin': typeof AuthGuardedAdminRoute
  '/store': typeof AuthGuardedStoreRoute
  '/register': typeof AuthRegisterRoute
  '/sign-in': typeof AuthSignInRoute
  '/users/$nickname': typeof UsersNicknameRoute
  '/users/id/$userId': typeof UsersIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/tutorial': typeof TutorialRouteRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth-guarded': typeof AuthGuardedRouteWithChildren
  '/bianca': typeof BiancaRoute
  '/leaderboard': typeof LeaderboardRoute
  '/_auth-guarded/me': typeof AuthGuardedMeRouteRoute
  '/_auth-guarded/admin': typeof AuthGuardedAdminRoute
  '/_auth-guarded/store': typeof AuthGuardedStoreRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/users/$nickname': typeof UsersNicknameRoute
  '/_auth-guarded/': typeof AuthGuardedIndexRoute
  '/users/id/$userId': typeof UsersIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/tutorial'
    | '/'
    | '/bianca'
    | '/leaderboard'
    | '/me'
    | '/admin'
    | '/store'
    | '/register'
    | '/sign-in'
    | '/users/$nickname'
    | '/users/id/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tutorial'
    | '/'
    | '/bianca'
    | '/leaderboard'
    | '/me'
    | '/admin'
    | '/store'
    | '/register'
    | '/sign-in'
    | '/users/$nickname'
    | '/users/id/$userId'
  id:
    | '__root__'
    | '/tutorial'
    | '/_auth'
    | '/_auth-guarded'
    | '/bianca'
    | '/leaderboard'
    | '/_auth-guarded/me'
    | '/_auth-guarded/admin'
    | '/_auth-guarded/store'
    | '/_auth/register'
    | '/_auth/sign-in'
    | '/users/$nickname'
    | '/_auth-guarded/'
    | '/users/id/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TutorialRouteRoute: typeof TutorialRouteRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthGuardedRoute: typeof AuthGuardedRouteWithChildren
  BiancaRoute: typeof BiancaRoute
  LeaderboardRoute: typeof LeaderboardRoute
  UsersNicknameRoute: typeof UsersNicknameRoute
  UsersIdUserIdRoute: typeof UsersIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bianca': {
      id: '/bianca'
      path: '/bianca'
      fullPath: '/bianca'
      preLoaderRoute: typeof BiancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guarded': {
      id: '/_auth-guarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guarded/': {
      id: '/_auth-guarded/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardedIndexRouteImport
      parentRoute: typeof AuthGuardedRoute
    }
    '/users/$nickname': {
      id: '/users/$nickname'
      path: '/users/$nickname'
      fullPath: '/users/$nickname'
      preLoaderRoute: typeof UsersNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth-guarded/store': {
      id: '/_auth-guarded/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthGuardedStoreRouteImport
      parentRoute: typeof AuthGuardedRoute
    }
    '/_auth-guarded/admin': {
      id: '/_auth-guarded/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthGuardedAdminRouteImport
      parentRoute: typeof AuthGuardedRoute
    }
    '/_auth-guarded/me': {
      id: '/_auth-guarded/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthGuardedMeRouteRouteImport
      parentRoute: typeof AuthGuardedRoute
    }
    '/users/id/$userId': {
      id: '/users/id/$userId'
      path: '/users/id/$userId'
      fullPath: '/users/id/$userId'
      preLoaderRoute: typeof UsersIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthGuardedRouteChildren {
  AuthGuardedMeRouteRoute: typeof AuthGuardedMeRouteRoute
  AuthGuardedAdminRoute: typeof AuthGuardedAdminRoute
  AuthGuardedStoreRoute: typeof AuthGuardedStoreRoute
  AuthGuardedIndexRoute: typeof AuthGuardedIndexRoute
}

const AuthGuardedRouteChildren: AuthGuardedRouteChildren = {
  AuthGuardedMeRouteRoute: AuthGuardedMeRouteRoute,
  AuthGuardedAdminRoute: AuthGuardedAdminRoute,
  AuthGuardedStoreRoute: AuthGuardedStoreRoute,
  AuthGuardedIndexRoute: AuthGuardedIndexRoute,
}

const AuthGuardedRouteWithChildren = AuthGuardedRoute._addFileChildren(
  AuthGuardedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TutorialRouteRoute: TutorialRouteRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthGuardedRoute: AuthGuardedRouteWithChildren,
  BiancaRoute: BiancaRoute,
  LeaderboardRoute: LeaderboardRoute,
  UsersNicknameRoute: UsersNicknameRoute,
  UsersIdUserIdRoute: UsersIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
