name: Lint, build and run tests

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          
      - name: Install packages
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --dev --frozen-lockfile

      - name: Check code
        run: yarn lint

  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          
      - name: Install packages
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --dev --frozen-lockfile

      - name: Build
        run: yarn build
