name: Lint, build and run tests

on:
  push:
  workflow_call:

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Packages
        run: yarn

      - name: Run linter
        run: yarn lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Packages
        run: yarn

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Packages
        run: yarn

      - name: Build
        run: yarn build
